### ISSUE TITLE
couldn't deploy profefe by docker-compose from master. 

### ISSUE THREAD

**Issue by Tsovak** [profefe/profefe#102]
couldn't deploy profefe by docker-compose from master. 

Step to reproduce:
1. pull master 
2. docker-compose up 
here is an invalid version 
```
  profefe:
    build:
      context: .
      dockerfile: contrib/docker/Dockerfile
      args:
        VERSION: dev
    image: profefe/profefe:latest
    command:
      - /profefe
      - -addr=:10100
      - -storage-type=${PROFEFE_STORAGE_TYPE:-badger}
    ports:
      - 10100:10100
```
output: 
`profefe_1  | 2020-09-07T09:55:40.791Z	error	profefe/main.go:45	storage configuration required`

I faced out that the `-badger.dir` parameter should be passed.
